backend:
  name: github
  repo: NCUSCC/blog-ncuscc  # 你的GitHub仓库名
  branch: main  # 使用的分支名

media_folder: "source/images"  # 媒体文件存储位置
public_folder: "/images"  # 媒体文件的公开访问路径

collections:
  - name: "post"  # 文章集合标识
    label: "Post"  # 显示名称
    folder: "source/_posts"  # 文章存储文件夹
    create: true  # 允许创建新文章
    fields:  # 文章字段设置
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}